### ISSUE TITLE
http://unknown-horizons.readthedocs.org/en/latest/

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/docs#6]
How to update: http://unknown-horizons.readthedocs.org/en/latest/

I fixed some links.

**Comment by LinuxDonald** [comment]
@squiddy @ChrisOelmueller maybe one of you can help please?

**Comment by squiddy** [comment]
I don't really remember. I think you can log into readthedocs and add a new project to be imported from GitHub. It listens for pushes then and rebuilds the documentation.

**Comment by LinuxDonald** [comment]
@squiddy could you add me please? http://readthedocs.org/projects/unknown-horizons/

nick LinuxDonald

**Comment by squiddy** [comment]
Done.

**Comment by LinuxDonald** [comment]
@squiddy maybe an idea how to fix that? http://readthedocs.org/projects/unknown-horizons/builds/5240005/

**Comment by LinuxDonald** [comment]
Disabled pdf build now it works.
